### ISSUE TITLE
hyper 0.12 support

### ISSUE THREAD

**Issue by lnicola** [scottlamb/http-serve#5]
It's out now. I tried to do a port a while ago, but got stuck for some reason.

**Comment by scottlamb** [comment]
I started something a while ago (should have opened this issue so you'd know what was going on, sorry). Lemme see how far I am from finishing it...

**Comment by lnicola** [comment]
Yeah, I figured when you asked about the `Body` conversion. Just wanted to let you know that hyper was out.
