### ISSUE TITLE
Consider publishing to crates.io

### ISSUE THREAD

**Issue by lnicola** [scottlamb/http-serve#6]
Basically, what the title says :smile:.

**Comment by scottlamb** [comment]
Yeah, I suppose there's no reason not to do it now. I will when I get a chance.

Any thoughts on the name? `http-serve` is the best I've got. /shruggie

Are you looking for API stability also? That might need some more work.

**Comment by lnicola** [comment]
> Any thoughts on the name?

I think it's fine -- naming is hard, anyway. I also liked `http-entity`, so I guess I'm not very discerning.

> Are you looking for API stability also?

No, a `0.1` is fine. It's just nice to not need a `git` dependency.

**Comment by lnicola** [comment]
Ping? :smile:

**Comment by scottlamb** [comment]
https://crates.io/crates/http-serve

That was easier than I thought it would be.
